---
title: "SAWS_upwelling"
author: "Amieroh Abrahams"
date: "29 August 2019"
output: html_document
---

# Load libraries

```{r}
library(ncdf4) # package for netcdf manipulation
library(raster) # package for raster manipulation
library(rgdal) # package for geospatial analysis
library(ggplot2) # package for plotting
library(stringr)
library(tidyverse)
library(reshape2)
library(lubridate)
library(data.table)
# library(plyr)
library(rWind)
```

# This code extracts the netCDF that I was given from SAWS

```{r}

# #          1         2         3         4
# # 12345678901234567890123456789012345678901
# # SA4_00Z_OPS_20190829_SUBSET.nc

ncFile <- '/home/amieroh/Documents/SAWS/SAWS/data/SA4_00Z_OPS_20190829.nc'  # This is just the path where the netCDF file lives. This will have to be changed accordingly

nc <- nc_open(ncFile)
 # pathLen <- nchar(paste0(ncDir, "/")) + 1
  fNameStem <-
    substr(basename(ncFile), 1, 12)
  fDate <- substr(basename(ncFile), 13, 20)
  x_wind <- ncvar_get(nc, varid = "x_wind") %>%
    round(4)
  y_wind <- ncvar_get(nc, varid = "y_wind") %>% 
    round(4)
  dimnames(x_wind) <- list(lon = nc$dim$lon$vals,
                        lat = nc$dim$lat$vals,
                        time = nc$dim$time$vals)
  dimnames(y_wind) <- list(lon = nc$dim$lon$vals,
                        lat = nc$dim$lat$vals)
  nc_close(nc)
  x_wind <- as_tibble(melt(x_wind, value.name = "x_wind"))
  y_wind <- as_tibble(melt(y_wind, value.name = "y_wind"))
  x_wind$time <- ymd(fDate)              # In 1970-01-01 00:00:00 format mutate(date = as.POSIXct(as.character(date), "%Y%m%d%H%M", tz = "Africa/Johannesburg")) 
  y_wind$time <- ymd(fDate)
  y_wind <- y_wind %>% 
    select(y_wind)
  na.omit(x_wind)
  na.omit(y_wind)
  x_wind <- x_wind %>% 
    select(lat, lon, x_wind,time)
  y_wind <- y_wind %>% 
    select(y_wind)
  combined_wind <- cbind(x_wind,y_wind) %>% 
  dplyr::rename(Vcomp = y_wind) %>% 
  dplyr::rename(Ucomp = x_wind)
  
# Saving the data in RData format (R format)
save(combined_wind, file = "combined_wind.RData")

# Using U and V components to determine the wind direction
windDir <- function(u, v) {
  if(v > 0)         ((180 / pi) * atan(u/v) + 180)
  if(u < 0 & v < 0) ((180 / pi) * atan(u/v) + 0)
  if(u > 0 & v < 0) ((180 / pi) * atan(u/v) + 360)
}

wind_direction <-ddply(combined_wind, 'time', summarize, windDir=windDir(Ucomp, Vcomp))
wind_direction <- wind_direction %>%
  select(windDir)
wind <- cbind(wind_direction,combined_wind) # New dataframe with the wind directions addded

# Next is to calculate wind speed (The upwelling formula requires wind speed)


```

```{r}
# Temperature data
# http://marine.copernicus.eu/services-portfolio/access-to-products/?option=com_csw&view=details&product_id=GLOBAL_ANALYSIS_FORECAST_PHY_001_024
# GLOBAL-ANALYSIS-FORECAST-PHY-001-024
# Manually downloaded a netCDF file from this website  using the following coordinates y: -25 and 25 ; x: -35 and 20 - This selects the Benguela region only
# When manually selecting the data Remove the variables to only have SST variables and then set the dates accordingly

# Downloads a netCDF: The code below extracts the data from the netCDFs

ncFile <- '/home/amieroh/Documents/SAWS/data/global-analysis-forecast-phy-001-024_1568709782139.nc'  # This makes reference to my directory. You will have to change this on your system

# #          1         2         3         4         5
# # 12345678901234567890123456789012345678901234567890123
# # global-analysis-forecast-phy-001-024_1568709782139.nc

nc <- nc_open(ncFile)
  fNameStem <-
    substr(basename(ncFile), 1, 50)
  #fDate <- substr(basename(ncFile), 13, 20)
  Temperature <- ncvar_get(nc, varid = "thetao") %>%
  round(4)
  dimnames(Temperature) <- list(lon = nc$dim$lon$vals,
                        lat = nc$dim$lat$vals)
  dimnames(Temperature) <- list(time = nc$dim$time$vals)
```


# Upwelling index

```{r}

# TO do:
# Get a dataset using the extracted datasets created above with daily temp and wind speed and direction in one column
# Create a column with the sites

Upwelling_index <- (wind_daily) %>%  # Making refeerence to the wind daily datta created above
  dplyr::rename(site = sites) %>%  # Renaming sites to site
  mutate(ui.saws = mean_speed * (cos(dir_circ - 160))) %>% # applying the ui formula
  drop_na %>% # removing the na values
  
# UI dataset produces the upwelling index
save(UI_angle, file = "Upwelling_index.csv")
```















